version: '3.8'

services:
  php:
    build: .
    container_name: msms_php
    ports:
      - "8080:80" # Map host port 8080 to container port 80
    volumes:
      # Mount the whole project directory to allow live code changes during development
      # Note: Adjust if your local structure is different or for production.
      - ./msms:/var/www/html/msms
      - ./SQL\ File:/var/www/html/SQL\ File
      - ./install.php:/var/www/html/install.php
      # If other root files/dirs exist and need to be mapped:
      # - ./some_other_file.php:/var/www/html/some_other_file.php
      # - ./some_other_dir:/var/www/html/some_other_dir
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: msms_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Change this in a real production environment
      MYSQL_DATABASE: msmsdb
      MYSQL_USER: msmsuser
      MYSQL_PASSWORD: msmspassword # Change this in a real production environment
    volumes:
      - ./sql_files/msmsdb.sql:/docker-entrypoint-initdb.d/msmsdb.sql
      - db_data:/var/lib/mysql # Persist database data
    networks:
      - app-network

volumes:
  db_data: # Named volume for MySQL data

networks:
  app-network:
    driver: bridge
